# ----
# Site

title: 山中方大侠
url: "https://photos.fangzenghong.com"
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: 
description: 摄影作品展示
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: 山中方大侠
  links:
    - https://photos.fangzenghong.com

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /uploads/1.jpg
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - deploy.sh

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true